### ISSUE TITLE
ImportError: /home/dancer/anaconda3/envs/new_toco/lib/python3.8/site-packages/_bilateralfilter.cpython-38-x86_64-linux-gnu.so: undefined symbol: omp_get_thread_num

### ISSUE THREAD

**Issue by Italy2006** [rulixiang/ToCo#18]
I'm sorry to bother you, but after I installed rloss according to your guidance, the following errors occurred after the import of this library

>>> import sys
>>> sys.path.append("/home/dancer/WeakSupervision/toco/rloss/pytorch/wrapper/bilateralfilter/build/lib.linux-x86_64-3.8")
>>> from bilateralfilter import bilateralfilter, bilateralfilter_batch
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/dancer/WeakSupervision/toco/rloss/pytorch/wrapper/bilateralfilter/bilateralfilter.py", line 15, in <module>
    import _bilateralfilter
ImportError: /home/dancer/anaconda3/envs/new_toco/lib/python3.8/site-packages/_bilateralfilter.cpython-38-x86_64-linux-gnu.so: undefined symbol: omp_get_thread_num

**Comment by xchouzhang** [comment]
> I'm sorry to bother you, but after I installed rloss according to your guidance, the following errors occurred after the import of this library
> 
> > > > import sys
> > > > sys.path.append("/home/dancer/WeakSupervision/toco/rloss/pytorch/wrapper/bilateralfilter/build/lib.linux-x86_64-3.8")
> > > > from bilateralfilter import bilateralfilter, bilateralfilter_batch
> > > > Traceback (most recent call last):
> > > > File "", line 1, in 
> > > > File "/home/dancer/WeakSupervision/toco/rloss/pytorch/wrapper/bilateralfilter/bilateralfilter.py", line 15, in 
> > > > import _bilateralfilter
> > > > ImportError: /home/dancer/anaconda3/envs/new_toco/lib/python3.8/site-packages/_bilateralfilter.cpython-38-x86_64-linux-gnu.so: undefined symbol: omp_get_thread_num
can it be solved?

**Comment by xchouzhang** [comment]
> I'm sorry to bother you, but after I installed rloss according to your guidance, the following errors occurred after the import of this library
> 
> > > > import sys
> > > > sys.path.append("/home/dancer/WeakSupervision/toco/rloss/pytorch/wrapper/bilateralfilter/build/lib.linux-x86_64-3.8")
> > > > from bilateralfilter import bilateralfilter, bilateralfilter_batch
> > > > Traceback (most recent call last):
> > > > File "", line 1, in 
> > > > File "/home/dancer/WeakSupervision/toco/rloss/pytorch/wrapper/bilateralfilter/bilateralfilter.py", line 15, in 
> > > > import _bilateralfilter
> > > > ImportError: /home/dancer/anaconda3/envs/new_toco/lib/python3.8/site-packages/_bilateralfilter.cpython-38-x86_64-linux-gnu.so: undefined symbol: omp_get_thread_num



@Italy2006 did you solve this problem?
